spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    check-template-location: true
  datasource:
    url: jdbc:mysql://localhost:3306/photogram?createDatabaseIfNotExist=true
    jdbc-url: jdbc:mysql://localhost:3303/photogram?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '@tnqh258'
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 128KB
      enabled: true
      location: file
server:
  port: 8080

file:
  path: D:/workspace/upload/