spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    check-template-location: true
  datasource:
    url: jdbc:mysql://localhost:3306/photogram?createDatabaseIfNotExist=true
    jdbc-url: jdbc:mysql://localhost:3303/photogram?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '@tnqh258'
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
server:
  port: 8080

